// Code generated by protoc-gen-grain. DO NOT EDIT.
// versions:
//  protoc-gen-grain v0.5.1
//  protoc           v4.25.3
// source: code/protos.proto

package grains

import (
	fmt "fmt"
	actor "github.com/asynkron/protoactor-go/actor"
	cluster "github.com/asynkron/protoactor-go/cluster"
	proto "google.golang.org/protobuf/proto"
	slog "log/slog"
	time "time"
)

var xVehicleFactory func() Vehicle

// VehicleFactory produces a Vehicle
func VehicleFactory(factory func() Vehicle) {
	xVehicleFactory = factory
}

// GetVehicleGrainClient instantiates a new VehicleGrainClient with given Identity
func GetVehicleGrainClient(c *cluster.Cluster, id string) *VehicleGrainClient {
	if c == nil {
		panic(fmt.Errorf("nil cluster instance"))
	}
	if id == "" {
		panic(fmt.Errorf("empty id"))
	}
	return &VehicleGrainClient{Identity: id, cluster: c}
}

// GetVehicleKind instantiates a new cluster.Kind for Vehicle
func GetVehicleKind(opts ...actor.PropsOption) *cluster.Kind {
	props := actor.PropsFromProducer(func() actor.Actor {
		return &VehicleActor{
			Timeout: 60 * time.Second,
		}
	}, opts...)
	kind := cluster.NewKind("Vehicle", props)
	return kind
}

// GetVehicleKind instantiates a new cluster.Kind for Vehicle
func NewVehicleKind(factory func() Vehicle, timeout time.Duration, opts ...actor.PropsOption) *cluster.Kind {
	xVehicleFactory = factory
	props := actor.PropsFromProducer(func() actor.Actor {
		return &VehicleActor{
			Timeout: timeout,
		}
	}, opts...)
	kind := cluster.NewKind("Vehicle", props)
	return kind
}

// Vehicle interfaces the services available to the Vehicle
type Vehicle interface {
	Init(ctx cluster.GrainContext)
	Terminate(ctx cluster.GrainContext)
	ReceiveDefault(ctx cluster.GrainContext)
	OnPosition(req *Position, ctx cluster.GrainContext) (*Empty, error)
}

// VehicleGrainClient holds the base data for the VehicleGrain
type VehicleGrainClient struct {
	Identity string
	cluster  *cluster.Cluster
}

// OnPosition requests the execution on to the cluster with CallOptions
func (g *VehicleGrainClient) OnPosition(r *Position, opts ...cluster.GrainCallOption) (*Empty, error) {
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 0, MessageData: bytes}
	resp, err := g.cluster.Request(g.Identity, "Vehicle", reqMsg, opts...)
	if err != nil {
		return nil, fmt.Errorf("error request: %w", err)
	}
	switch msg := resp.(type) {
	case *Empty:
		return msg, nil
	case *cluster.GrainErrorResponse:
		if msg == nil {
			return nil, nil
		}
		return nil, msg
	default:
		return nil, fmt.Errorf("unknown response type %T", resp)
	}
}

// VehicleActor represents the actor structure
type VehicleActor struct {
	ctx     cluster.GrainContext
	inner   Vehicle
	Timeout time.Duration
}

// Receive ensures the lifecycle of the actor for the received message
func (a *VehicleActor) Receive(ctx actor.Context) {
	switch msg := ctx.Message().(type) {
	case *actor.Started: //pass
	case *cluster.ClusterInit:
		a.ctx = cluster.NewGrainContext(ctx, msg.Identity, msg.Cluster)
		a.inner = xVehicleFactory()
		a.inner.Init(a.ctx)

		if a.Timeout > 0 {
			ctx.SetReceiveTimeout(a.Timeout)
		}
	case *actor.ReceiveTimeout:
		ctx.Poison(ctx.Self())
	case *actor.Stopped:
		a.inner.Terminate(a.ctx)
	case actor.AutoReceiveMessage: // pass
	case actor.SystemMessage: // pass

	case *cluster.GrainRequest:
		switch msg.MethodIndex {
		case 0:
			req := &Position{}
			err := proto.Unmarshal(msg.MessageData, req)
			if err != nil {
				ctx.Logger().Error("[Grain] OnPosition(Position) proto.Unmarshal failed.", slog.Any("error", err))
				resp := cluster.NewGrainErrorResponse(cluster.ErrorReason_INVALID_ARGUMENT, err.Error()).
					WithMetadata(map[string]string{
						"argument": req.String(),
					})
				ctx.Respond(resp)
				return
			}

			r0, err := a.inner.OnPosition(req, a.ctx)
			if err != nil {
				resp := cluster.FromError(err)
				ctx.Respond(resp)
				return
			}
			ctx.Respond(r0)
		}
	default:
		a.inner.ReceiveDefault(a.ctx)
	}
}

// onError should be used in ctx.ReenterAfter
// you can just return error in reenterable method for other errors
func (a *VehicleActor) onError(err error) {
	resp := cluster.FromError(err)
	a.ctx.Respond(resp)
}

var xOpportunityFactory func() Opportunity

// OpportunityFactory produces a Opportunity
func OpportunityFactory(factory func() Opportunity) {
	xOpportunityFactory = factory
}

// GetOpportunityGrainClient instantiates a new OpportunityGrainClient with given Identity
func GetOpportunityGrainClient(c *cluster.Cluster, id string) *OpportunityGrainClient {
	if c == nil {
		panic(fmt.Errorf("nil cluster instance"))
	}
	if id == "" {
		panic(fmt.Errorf("empty id"))
	}
	return &OpportunityGrainClient{Identity: id, cluster: c}
}

// GetOpportunityKind instantiates a new cluster.Kind for Opportunity
func GetOpportunityKind(opts ...actor.PropsOption) *cluster.Kind {
	props := actor.PropsFromProducer(func() actor.Actor {
		return &OpportunityActor{
			Timeout: 60 * time.Second,
		}
	}, opts...)
	kind := cluster.NewKind("Opportunity", props)
	return kind
}

// GetOpportunityKind instantiates a new cluster.Kind for Opportunity
func NewOpportunityKind(factory func() Opportunity, timeout time.Duration, opts ...actor.PropsOption) *cluster.Kind {
	xOpportunityFactory = factory
	props := actor.PropsFromProducer(func() actor.Actor {
		return &OpportunityActor{
			Timeout: timeout,
		}
	}, opts...)
	kind := cluster.NewKind("Opportunity", props)
	return kind
}

// Opportunity interfaces the services available to the Opportunity
type Opportunity interface {
	Init(ctx cluster.GrainContext)
	Terminate(ctx cluster.GrainContext)
	ReceiveDefault(ctx cluster.GrainContext)
	GetOpportunity(req *GetOpportunityRequest, ctx cluster.GrainContext) (*GetOpportunityResponse, error)
}

// OpportunityGrainClient holds the base data for the OpportunityGrain
type OpportunityGrainClient struct {
	Identity string
	cluster  *cluster.Cluster
}

// GetOpportunity requests the execution on to the cluster with CallOptions
func (g *OpportunityGrainClient) GetOpportunity(r *GetOpportunityRequest, opts ...cluster.GrainCallOption) (*GetOpportunityResponse, error) {
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 0, MessageData: bytes}
	resp, err := g.cluster.Request(g.Identity, "Opportunity", reqMsg, opts...)
	if err != nil {
		return nil, fmt.Errorf("error request: %w", err)
	}
	switch msg := resp.(type) {
	case *GetOpportunityResponse:
		return msg, nil
	case *cluster.GrainErrorResponse:
		if msg == nil {
			return nil, nil
		}
		return nil, msg
	default:
		return nil, fmt.Errorf("unknown response type %T", resp)
	}
}

// OpportunityActor represents the actor structure
type OpportunityActor struct {
	ctx     cluster.GrainContext
	inner   Opportunity
	Timeout time.Duration
}

// Receive ensures the lifecycle of the actor for the received message
func (a *OpportunityActor) Receive(ctx actor.Context) {
	switch msg := ctx.Message().(type) {
	case *actor.Started: //pass
	case *cluster.ClusterInit:
		a.ctx = cluster.NewGrainContext(ctx, msg.Identity, msg.Cluster)
		a.inner = xOpportunityFactory()
		a.inner.Init(a.ctx)

		if a.Timeout > 0 {
			ctx.SetReceiveTimeout(a.Timeout)
		}
	case *actor.ReceiveTimeout:
		ctx.Poison(ctx.Self())
	case *actor.Stopped:
		a.inner.Terminate(a.ctx)
	case actor.AutoReceiveMessage: // pass
	case actor.SystemMessage: // pass

	case *cluster.GrainRequest:
		switch msg.MethodIndex {
		case 0:
			req := &GetOpportunityRequest{}
			err := proto.Unmarshal(msg.MessageData, req)
			if err != nil {
				ctx.Logger().Error("[Grain] GetOpportunity(GetOpportunityRequest) proto.Unmarshal failed.", slog.Any("error", err))
				resp := cluster.NewGrainErrorResponse(cluster.ErrorReason_INVALID_ARGUMENT, err.Error()).
					WithMetadata(map[string]string{
						"argument": req.String(),
					})
				ctx.Respond(resp)
				return
			}

			r0, err := a.inner.GetOpportunity(req, a.ctx)
			if err != nil {
				resp := cluster.FromError(err)
				ctx.Respond(resp)
				return
			}
			ctx.Respond(r0)
		}
	default:
		a.inner.ReceiveDefault(a.ctx)
	}
}

// onError should be used in ctx.ReenterAfter
// you can just return error in reenterable method for other errors
func (a *OpportunityActor) onError(err error) {
	resp := cluster.FromError(err)
	a.ctx.Respond(resp)
}

var xOrganizationFactory func() Organization

// OrganizationFactory produces a Organization
func OrganizationFactory(factory func() Organization) {
	xOrganizationFactory = factory
}

// GetOrganizationGrainClient instantiates a new OrganizationGrainClient with given Identity
func GetOrganizationGrainClient(c *cluster.Cluster, id string) *OrganizationGrainClient {
	if c == nil {
		panic(fmt.Errorf("nil cluster instance"))
	}
	if id == "" {
		panic(fmt.Errorf("empty id"))
	}
	return &OrganizationGrainClient{Identity: id, cluster: c}
}

// GetOrganizationKind instantiates a new cluster.Kind for Organization
func GetOrganizationKind(opts ...actor.PropsOption) *cluster.Kind {
	props := actor.PropsFromProducer(func() actor.Actor {
		return &OrganizationActor{
			Timeout: 60 * time.Second,
		}
	}, opts...)
	kind := cluster.NewKind("Organization", props)
	return kind
}

// GetOrganizationKind instantiates a new cluster.Kind for Organization
func NewOrganizationKind(factory func() Organization, timeout time.Duration, opts ...actor.PropsOption) *cluster.Kind {
	xOrganizationFactory = factory
	props := actor.PropsFromProducer(func() actor.Actor {
		return &OrganizationActor{
			Timeout: timeout,
		}
	}, opts...)
	kind := cluster.NewKind("Organization", props)
	return kind
}

// Organization interfaces the services available to the Organization
type Organization interface {
	Init(ctx cluster.GrainContext)
	Terminate(ctx cluster.GrainContext)
	ReceiveDefault(ctx cluster.GrainContext)
	OnPosition(req *Position, ctx cluster.GrainContext) (*Empty, error)
	GetGeofences(req *GetGeofencesRequest, ctx cluster.GrainContext) (*GetGeofencesResponse, error)
}

// OrganizationGrainClient holds the base data for the OrganizationGrain
type OrganizationGrainClient struct {
	Identity string
	cluster  *cluster.Cluster
}

// OnPosition requests the execution on to the cluster with CallOptions
func (g *OrganizationGrainClient) OnPosition(r *Position, opts ...cluster.GrainCallOption) (*Empty, error) {
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 0, MessageData: bytes}
	resp, err := g.cluster.Request(g.Identity, "Organization", reqMsg, opts...)
	if err != nil {
		return nil, fmt.Errorf("error request: %w", err)
	}
	switch msg := resp.(type) {
	case *Empty:
		return msg, nil
	case *cluster.GrainErrorResponse:
		if msg == nil {
			return nil, nil
		}
		return nil, msg
	default:
		return nil, fmt.Errorf("unknown response type %T", resp)
	}
}

// GetGeofences requests the execution on to the cluster with CallOptions
func (g *OrganizationGrainClient) GetGeofences(r *GetGeofencesRequest, opts ...cluster.GrainCallOption) (*GetGeofencesResponse, error) {
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 1, MessageData: bytes}
	resp, err := g.cluster.Request(g.Identity, "Organization", reqMsg, opts...)
	if err != nil {
		return nil, fmt.Errorf("error request: %w", err)
	}
	switch msg := resp.(type) {
	case *GetGeofencesResponse:
		return msg, nil
	case *cluster.GrainErrorResponse:
		if msg == nil {
			return nil, nil
		}
		return nil, msg
	default:
		return nil, fmt.Errorf("unknown response type %T", resp)
	}
}

// OrganizationActor represents the actor structure
type OrganizationActor struct {
	ctx     cluster.GrainContext
	inner   Organization
	Timeout time.Duration
}

// Receive ensures the lifecycle of the actor for the received message
func (a *OrganizationActor) Receive(ctx actor.Context) {
	switch msg := ctx.Message().(type) {
	case *actor.Started: //pass
	case *cluster.ClusterInit:
		a.ctx = cluster.NewGrainContext(ctx, msg.Identity, msg.Cluster)
		a.inner = xOrganizationFactory()
		a.inner.Init(a.ctx)

		if a.Timeout > 0 {
			ctx.SetReceiveTimeout(a.Timeout)
		}
	case *actor.ReceiveTimeout:
		ctx.Poison(ctx.Self())
	case *actor.Stopped:
		a.inner.Terminate(a.ctx)
	case actor.AutoReceiveMessage: // pass
	case actor.SystemMessage: // pass

	case *cluster.GrainRequest:
		switch msg.MethodIndex {
		case 0:
			req := &Position{}
			err := proto.Unmarshal(msg.MessageData, req)
			if err != nil {
				ctx.Logger().Error("[Grain] OnPosition(Position) proto.Unmarshal failed.", slog.Any("error", err))
				resp := cluster.NewGrainErrorResponse(cluster.ErrorReason_INVALID_ARGUMENT, err.Error()).
					WithMetadata(map[string]string{
						"argument": req.String(),
					})
				ctx.Respond(resp)
				return
			}

			r0, err := a.inner.OnPosition(req, a.ctx)
			if err != nil {
				resp := cluster.FromError(err)
				ctx.Respond(resp)
				return
			}
			ctx.Respond(r0)
		case 1:
			req := &GetGeofencesRequest{}
			err := proto.Unmarshal(msg.MessageData, req)
			if err != nil {
				ctx.Logger().Error("[Grain] GetGeofences(GetGeofencesRequest) proto.Unmarshal failed.", slog.Any("error", err))
				resp := cluster.NewGrainErrorResponse(cluster.ErrorReason_INVALID_ARGUMENT, err.Error()).
					WithMetadata(map[string]string{
						"argument": req.String(),
					})
				ctx.Respond(resp)
				return
			}

			r0, err := a.inner.GetGeofences(req, a.ctx)
			if err != nil {
				resp := cluster.FromError(err)
				ctx.Respond(resp)
				return
			}
			ctx.Respond(r0)
		}
	default:
		a.inner.ReceiveDefault(a.ctx)
	}
}

// onError should be used in ctx.ReenterAfter
// you can just return error in reenterable method for other errors
func (a *OrganizationActor) onError(err error) {
	resp := cluster.FromError(err)
	a.ctx.Respond(resp)
}

func respond[T proto.Message](ctx cluster.GrainContext) func(T) {
	return func(resp T) {
		ctx.Respond(resp)
	}
}
